---
title: "HW 4"
author: "Sebastian Alzate Vargas"
date: "16/9/2021"
output:
  pdf_document: default
  html_document: default
---

## Problem 1:

Let $(X,Y)$ be a random vector with joint density $f(x,y)= cx/y^2$, $1<x<y<2.$ 

a. Find c
 
b. Find $F_X(1.5)$
 
c. Find $P(Y<1.5|X=1.25)$
 

#### Solution
a. Encontremos el valor de $c$ de la siguiente forma

  \begin{align*}
  1=\int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \dfrac{cx}{y^2} dxdy &=   \int_{1}^{2} \int_{1}^{y} \dfrac{cx}{y^2} dxdy\\
  &=  c\int_{1}^{2}     \left(\dfrac{x^2}{2y^2}\right)_1^ydy\\
  &=c\int_{1}^{2} \left(\dfrac{1}{2} - \dfrac{1}{2y^2}\right)dy\\
  &= c\left(\dfrac{y}{2}+\dfrac{1}{2y}\right)_1^2\\
  &= c\left(\dfrac{5}{4}-1\right)\\
  &= c\dfrac{1}{4}
  \end{align*}

Por tanto, $c=4$


b. Encontremos la marginal

   \begin{align*}
    f_X(x)= \int_{-\infty}^{\infty} f(x,y)dy &= \int_x^2 f(x,y)dy \\
    &=  \int_x^2\dfrac{4x}{y^2}dy \\
    &= \left(-\dfrac{4x}{y}\right)_x^2 \\
    &= 4x\left( -\frac{1}{2} + \frac{1}{x} \right)\\
    &= 2(2-x)
   \end{align*}

Entonces la funci칩n de distribuci칩n esta dada por:

   \begin{align*}
    F_X(x)&= \int_{-\infty}^{x} f_X(t)dt \\
    &=\int_{1}^{x} 2(2-t)dt \\
    &= -(2-t)^2|_1^x \\
    &= -(2-x)^2+1 \\
   \end{align*}
   
Entonces,

$F_x(1.5)=-(2-1.5)^2+1=-0.5^2+1=-0.25+1=0.75$


c.

   \begin{align*}
    f_{Y|X=x}(y|x) = \frac{f(x,y)}{f_X(x)}= \dfrac{4x/y^2}{2(2-x)}=   \dfrac{2x}{(2-x)y^2} \\ \\
   \end{align*}


Entonces
  
   $$f_{Y|X=1.25}(y|1.25)= \dfrac{2(1.25)}{(2-1.25)y^2}=\frac{10}{3y^2} \\$$


Como $x<y$ y $x=1.25$ entonces $1.25<y$ 
  \begin{align*}
P(Y<1.5|X=1.25)&= \int_{1.25}^{1.5} \frac{10}{3y^2}dy\\
&=-\dfrac{10}{3y}\vert_{1.25}^{1.5}\\
&=-\dfrac{20}{9}+\dfrac{8}{3}\\
&=\dfrac{4}{9}\\
&=0.\overline{4}
  \end{align*}
  
  
## Problem 2
We roll three fair dice. Let X be the smallest of the three rolls and Y the largest. Find the joint density of $(X,Y)$. Find $F(2,4)$.


#### Solution
Sea $X$ el numero mas peque침o de los tres dados y $Y$ el m치s grande,

Notemos lo siguiente:

Si $x>y$, entonces

$$f_{XY}(x,y)=0$$

Si $x=y$, los tres dados salieron igual

$$f_{XY}(x,y)=P(X=x,Y=x)=\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}=\dfrac{1}{216}$$

Si $y=x+1$, el tercer resultado es igual a $x$ o $y$
\begin{align*}
   f_{XY}(x,y)=P(X=x,Y=x+1)&=\dfrac{3!}{1!2!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}+\dfrac{3!}{1!2!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}\\
   &=\dfrac{6}{216} 
\end{align*}

Si $y=x+2$, Caso anterior $+$ el tercer resultado es igual a $x+1$
\begin{align*}
   f_{XY}(x,y)=P(X=x,Y=x+2)&=\dfrac{6}{216}+\dfrac{3!}{1!1!1!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}\\
   &=\dfrac{12}{216} 
\end{align*}

Si $y=x+3$, Caso anterior $+$ el tercer resultado es igual a $x+2$
\begin{align*}
   f_{XY}(x,y)=P(X=x,Y=x+3)&=\dfrac{12}{216}+\dfrac{3!}{1!1!1!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}\\
   &=\dfrac{18}{216} 
\end{align*}

Si $y=x+4$, Caso anterior $+$ el tercer resultado es igual a $x+3$
\begin{align*}
   f_{XY}(x,y)=P(X=x,Y=x+4)&=\dfrac{18}{216}+\dfrac{3!}{1!1!1!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}\\
   &=\dfrac{24}{216} 
\end{align*}

Si $y=x+5$, Caso anterior $+$ el tercer resultado es igual a $x+4$
\begin{align*}
   f_{XY}(x,y)=P(X=x,Y=x+5)&=\dfrac{24}{216}+\dfrac{3!}{1!1!1!}\dfrac{1}{6}\dfrac{1}{6}\dfrac{1}{6}\\
   &=\dfrac{30}{216} 
\end{align*}

la conjunta es:
$$
\setlength{\tabcolsep}{0.5em} % for the horizontal padding
{\renewcommand{\arraystretch}{1.3}
\begin{tabular}{|c|c|c|c|c|c|c|}
\hline
$X/Y$ & 1 & 2 & 3 & 4 & 5 & 6 \\ \hline
1     & $\frac{1}{216}$  & $\frac{6}{216}$  & $\frac{12}{216}$  & $\frac{18}{216}$  & $\frac{24}{216}$  & $\frac{30}{216}$  \\ \hline
2     &  0 & $\frac{1}{216}$  & $\frac{6}{216}$  & $\frac{12}{216}$  & $\frac{18}{216}$  & $\frac{24}{216}$  \\ \hline
3     &  0 &  0 & $\frac{1}{216}$  & $\frac{6}{216}$  & $\frac{12}{216}$  & $\frac{18}{216}$  \\ \hline
4     &  0 &  0 &  0 & $\frac{1}{216}$  & $\frac{6}{216}$  & $\frac{12}{216}$  \\ \hline
5     &  0 &  0 &  0 &  0 & $\frac{1}{216}$  & $\frac{6}{216}$  \\ \hline
6     &  0 &  0 &  0 &  0 & 0  & $\frac{1}{216}$  \\ \hline
\end{tabular}}$$


Ahora,
\begin{align*}
    F(2,4) &= P(X\leq 2, Y\leq 4) \\
    &= P(X=1,Y\leq 4)+P(X=2,Y\leq 4)\\
    &= P(X=1,Y=1)+P(X=1,Y=2)+P(X=1,Y=3)+P(X=1,Y=4)\\
    &+ P(X=2,Y=1)+P(X=2,Y=2)+P(X=2,Y=3)+P(X=2,Y=4) \\
    &= \frac{1}{216}+\frac{6}{216}+\frac{12}{216}+\frac{18}{216}+0+\frac{1}{216}+\frac{6}{216}+\frac{12}{216} \\
    &= \frac{7}{27} \\
    &\approx 0.259
\end{align*}


## Problem 3
Say $X\sim U[0,1]$ and $Y|X=x\sim U[x,1]$

a. Find $f_{X,Y}(x,y)$

b. Find $f_Y(y)$

c. Find $f_{X|Y=y}(x|y)$ and $F_{X|Y=0.6}(0.4|0.6)$

#### Solution

a. Tenemos que $f_X(x)=\dfrac{1}{1-0}=1$ y $f_{Y\vert X=x}(Y\vert x)=\dfrac{1}{1-x}$ 
\begin{align*}
f(x,y) &= f_{Y|X=x}(y|x)f_X(x)\\ 
  &= \dfrac{1}{1-x}\cdot1\\ 
  &= \dfrac{1}{1-x}
\end{align*}

b. \begin{align*}
    f_Y(y)&=\int_{-\infty}^{\infty} f_{XY}(x,y)dx\\
    &=\int_{0}^{y}\dfrac{1}{1-x}dx\\
    &= -\ln (1-x)^y_0\\
    &=-ln(1-y)
  \end{align*}

c. $f_{X|Y=y}(x|y) = \dfrac{f(x,y)}{f_Y(y)}= \dfrac{1}{(x-1)ln(1-y)}$

Entonces,

\begin{align*}
    F_{X|Y=y}(x|y) &= P(X\leq x| Y=y) \\
    &= \int_{-\infty}^x f_{X|Y=y}(t|y) dt \\
    &= \int_{0}^x \dfrac{1}{(t-1)ln(1-y)} dx \\
    &= \frac{ln(1-x)}{ln(1-y)}
\end{align*}

Por tanto,

$$F_{X|Y=0.6}(0.4|0.6) = \frac{ln(1-0.4)}{ln(1-0.6)}=0.5574$$

